### ISSUE TITLE
Call-time pass-by-reference error in 4.6 version

### ISSUE THREAD

**Issue by Upperholme** [compucorp/uk.co.compucorp.civicrm.giftaid#21]
When I submit a test contribution page with the 4.6 version of the extension installed I get a white screen in response and the following error is generated:

PHP Fatal error:  Call-time pass-by-reference has been removed in /home/sites/default/wp-content/plugins/files/civicrm/extensions/uk.co.compucorp.civicrm.giftaid-civi4.6/CRM/Civigiftaid/Utils/Hook.php on line 107, referer: http://example.com/?page=CiviCRM&q=civicrm%2Fcontribute%2Ftransact&reset=1&id=1&action=preview

If I edit the line to read as below:
        return self::singleton()->invoke($numParams, $arg1, $arg2, $arg3, $arg4, $arg5, $arg6, $fnSuffix);
 and resubmit I get the following error:

PHP Fatal error:  Call-time pass-by-reference has been removed in /home/sites/default/wp-content/plugins/files/civicrm/extensions/uk.co.compucorp.civicrm.giftaid-civi4.6/CRM/Civigiftaid/Utils/Hook.php on line 110, referer: http://example.com/163-2/

Editing line 110 in the same way, so it reads:
        return self::singleton()->invoke($numParams, $arg1, $arg2, $arg3, $arg4, $arg6, $fnSuffix);
 seems to resolve it. 

I think this is a result of using a newer release of PHP. 5.3 was content with the line as it was, but 5.4+, which is a strong recommendation for Civi 4.6 throws the error.

I'm not a coder, by the way.

**Comment by guanhuan** [comment]
Hi @Upperholme,

Which version/branch of GiftAid are you using? What is your CiviCRM version?

Best

Guanhuan

**Comment by gibsonoliver** [comment]
Hi Guanhuan

I'm getting the same message.
Fatal error: Call-time pass-by-reference has been removed in /home/forwardu/www/www/wp-content/plugins/files/civicrm/extensions/uk.co.compucorp.civicrm.giftaid-3.0alpha2/uk.co.compucorp.civicrm.giftaid-3.0alpha2/CRM/Civigiftaid/Utils/Hook.php on line 107

On a Wordpress site (4.3.1) and CiviCRM 4.6.10

Cheers
Olly

**Comment by guanhuan** [comment]
Hi @Upperholme 

Sorry for the delay on reply. This issue has been addressed in the latest beta release. Please upgrade to https://github.com/compucorp/uk.co.compucorp.civicrm.giftaid/releases/tag/v3.0beta and let us know if the problem persists.

Best

Guanhuan

**Comment by guanhuan** [comment]
Closed as lack of activity
