### ISSUE TITLE
v3 Alpha3 version does not show all available financial types!!

### ISSUE THREAD

**Issue by tapashdatta** [compucorp/uk.co.compucorp.civicrm.giftaid#28]
I have just upgraded to alpha 3. Thank you for this. But When I go to Global settings (Administer >> CiviGiftAid >> Settings), it only shows a certain number of financial types. i.e. I have around 25 + 4 default  Financial type, but in the list only 25 of them are available to select manually. Some disabled financial types also shows up in the list.

**Comment by tapashdatta** [comment]
To test, I have added a new financial type after installing the extension, it does not show up in the "Globally enabled settings" either.

**Comment by guanhuan** [comment]
Hi @tapashdatta,

Thanks for letting us know. I think this is due to the default limit of CiviCRM api. We will plan and get this fixed shortly.

Best

Guanhuan
