### ISSUE TITLE
Adding to gift aid batch issue

### ISSUE THREAD

**Issue by gibsonoliver** [compucorp/uk.co.compucorp.civicrm.giftaid#30]
Hi

We have 2 clients who have the latest version installed. In both cases when they try to create a batch they get an error. 

The specific error text is
'“Fatal error: Call-time pass-by-reference has been removed in ...www/sites/default/files/civicrm/extensions/uk.co.compucorp.civicrm.giftaid-3.0alpha2/CRM/Civigiftaid/Utils/Hook.php on line 107”.''

One of the clients is perfectly happy to run some tests etc if this helps

Olly

**Comment by guanhuan** [comment]
Hi Ollie,

This looks like a PHP version problem. The error shows a deprecated syntax in PHP 5.3 being marked as fatal error in later versions.

Could you confirm the PHP version your sites are running on and we will check if the issue persists in the latest development?

Much appreciated.

Best

Guanhuan

**Comment by gibsonoliver** [comment]
Hi Guanhuan

Its 5.6.21

Olly

On 17 May 2016 at 11:46, Guanhuan <notifications@github.com> wrote:

> Hi Ollie,
>
> This looks like a PHP version problem. The error shows a deprecated syntax
> in PHP 5.3 being marked as fatal error in later versions.
>
> Could you confirm the PHP version your sites are running on and we will
> check if the issue persists in the latest development?
>
> Much appreciated.
>
> Best
>
> Guanhuan
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/compucorp/uk.co.compucorp.civicrm.giftaid/issues/30#issuecomment-219682927>
>



-- 
Oliver Gibson
Director, Northbridge Digital Ltd

Mobile: +44(0) 7830 247789
Office: 01457 238876
UK Company Number: 08356302
UK VAT Number: 213 8467 10
Website: www.northbridgedigital.co.uk
<http://www.northbridgedigital.co.uk/>
Skype: gibsonoliver

**Comment by guanhuan** [comment]
Hi Ollie,

Sorry for the delay on reply. This issue has been addressed in the latest beta release. Please upgrade to https://github.com/compucorp/uk.co.compucorp.civicrm.giftaid/releases/tag/v3.0beta and let us know if the problem persists.

Best

Guanhuan

**Comment by guanhuan** [comment]
Closed due to lack of activity. Please feel free to reopen this issue if it persists.
