### ISSUE TITLE
Version compatibility query

### ISSUE THREAD

**Issue by Upperholme** [compucorp/uk.co.compucorp.civicrm.giftaid#33]
https://civicrm.org/extensions/gift-aid-extension-uk suggests that this extension is compatible with version 4.4 of CiviCRM. 
#21 and #30 imply that there may be outstanding issues with more recent versions of Civi and/or problems with specific PHP versions. Can anyone clarify/confirm which versions of CiviCRM this extension currently works with? And what it needs in terms of PHP?

Thanks.

**Comment by guanhuan** [comment]
Hi @Upperholme ,

The new beta version of GiftAid extension should be fully compatible with CiviCRM 4.6 and PHP 5.4+. We added some implementation with hope to make it compatible with 4.4 and 4.7 as well. If you are interested in testing the extension with any version other than CiviCRM 4.6, please feel free to feed back any issue you encountered.

Thanks.

Best

**Comment by guanhuan** [comment]
Closed as lack of activity
