### ISSUE TITLE
Trying to install in 4.7  DB Error: no such field

### ISSUE THREAD

**Issue by alanef** [compucorp/uk.co.compucorp.civicrm.giftaid#35]
Database Error Code: Unknown column 'batch_name' in 'civicrm_value_gift_aid_submission', 1054
Additional Details:
Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

```
[code] => -19
[message] => DB Error: no such field
[mode] => 16
[debug_info] => ALTER TABLE  `civicrm_value_gift_aid_submission` CHANGE  `batch_name`  `batch_name` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL [nativecode=1054 ** Unknown column 'batch_name' in 'civicrm_value_gift_aid_submission']
[type] => DB_Error
[user_info] => ALTER TABLE  `civicrm_value_gift_aid_submission` CHANGE  `batch_name`  `batch_name` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL [nativecode=1054 ** Unknown column 'batch_name' in 'civicrm_value_gift_aid_submission']
[to_string] => [db_error: message="DB Error: no such field" code=-19 mode=callback callback=CRM_Core_Error::handle prefix="" info="ALTER TABLE  `civicrm_value_gift_aid_submission` CHANGE  `batch_name`  `batch_name` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL [nativecode=1054 ** Unknown column 'batch_name' in 'civicrm_value_gift_aid_submission']"]
```

)

**Comment by guanhuan** [comment]
Hi @alanef ,

Please supply the following info to help us analyse the issue:
 - Giftaid version
 - CiviCRM version
 - PHP version

Thanks

**Comment by alanef** [comment]
Giftaid version  - latest
Civi 4.7.11 (latest - Wordpress)
PHP 5.6.24

**Comment by alanef** [comment]
I believed I used the latest master - I will try the beta in due course. Thanks

**Comment by guanhuan** [comment]
Hi @alanef ,

Any update on this? A few minor fixes have been committed to the develop branch. You can try them out as well.

Please feel free to reopen this ticket if the issue persists.
