### ISSUE TITLE
version 3 beta release doesn't appear in the in-app listing

### ISSUE THREAD

**Issue by Upperholme** [compucorp/uk.co.compucorp.civicrm.giftaid#36]
I'm just in process of getting the version 3.0 beta release installed and tested in a Civi 4.6 site. Just wanted to alert you - you may well already know - that this module/version is not listed in the in-app list of available extensions for 4.6, and also the directory listing at https://civicrm.org/extensions/gift-aid-extension-uk does not mention the existence of this beta release. I would guess that if the existence of the module was made public via these two channels, you'd probably get a bigger take-up from users? Or maybe you are preferring to wait until a stable release is finalised?

**Comment by guanhuan** [comment]
@Upperholme 
Thanks for the advise, the extension has all three version of CiviCRM added in the compatibility list. It has now been published onto CiviCRM.org extension directory.
