### ISSUE TITLE
SQL Parameters in recent update in wrong order?

### ISSUE THREAD

**Issue by TomCrawshaw** [compucorp/uk.co.compucorp.civicrm.giftaid#82]
In the latest version of CRM/CiviGiftAid/Utils/GiftAid.php there is a modification to the SQL to conditionally Update as well as Insert, but I think the parameters in the UPDATE are in the wrong order. Please could you check.
 
 `     if ($count == 0) {
        // Insert
        $sql = "
        INSERT INTO civicrm_value_gift_aid_submission (entity_id, eligible_for_gift_aid, amount, gift_aid_amount, batch_name)
        VALUES (%1, %2, NULL, NULL, NULL)";
      }
      else {
        // Update
        $sql = "
        UPDATE civicrm_value_gift_aid_submission
        SET eligible_for_gift_aid = %1
        WHERE entity_id = %2";
      }

      $queryParams = array(
        1 => array($params['entity_id'], 'Integer'),
        2 => array($params['eligible_for_gift_aid'], 'Integer'),
      );  
      $dao = CRM_Core_DAO::executeQuery( $sql, $queryParams );
    }`

**Comment by erawat** [comment]
@TomCrawshaw  this bug has been fixed on release version 3.0.4
